#!/bin/sh

PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
DAEMON=/usr/bin/monitor-recobtn
NAME=monitor-recobtn
DESC="Monitor-recobtn daemon"
ARGS="/usr/bin/factory_config_reset.sh"

set -e

test -x "$DAEMON" || exit 0
#GPIO2_3 Recovery 
if [ ! -e /sys/class/gpio/gpio67 ]; then
	echo 67 > /sys/class/gpio/export
	echo in > /sys/class/gpio/gpio67/direction
fi
#GPIO2_2 Green
if [ ! -e /sys/class/gpio/gpio66 ]; then
	echo 66 > /sys/class/gpio/export
fi
	echo out > /sys/class/gpio/gpio66/direction

#GPIO2_5 Red
if [ ! -e /sys/class/gpio/gpio69 ]; then
	echo 69 > /sys/class/gpio/export
fi	
	echo out > /sys/class/gpio/gpio69/direction

do_start() {
        start-stop-daemon -b -S -x $DAEMON -- $ARGS
}

do_stop() {
        killall -9 $NAME
}
case "$1" in
  start)
        echo -n "Starting $DESC: "
	do_start
        echo "$NAME."
        ;;
  stop)
        echo -n "Stopping $DESC: "
	do_stop
        echo "$NAME."
        ;;
  restart|force-reload)
        echo -n "Restarting $DESC: "
        do_stop
        do_start
        echo "$NAME."
        ;;
  *)
        N=/etc/init.d/$NAME
        echo "Usage: $N {start|stop|restart|force-reload}" >&2
        exit 1
        ;;
esac

exit 0
